# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: centos:centos6
      # - image: mhart/alpine-node:8
      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.4.4

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-
      - run:
          name: Add node to repo
          command: curl -sL https://rpm.nodesource.com/setup_8.x | bash -
      - run: curl http://people.centos.org/tru/devtools-2/devtools-2.repo -o /etc/yum.repos.d/devtools-2.repo | bash -
      - run:
          name: Install native dependencies
          command: yum install -y nodejs cairo cairo-devel libjpeg-turbo-devel pango pango-devel giflib-devel
      - run: yum install -y devtoolset-2-gcc devtoolset-2-binutils
      - run: yum install -y devtoolset-2-gcc-c++ devtoolset-2-gcc-gfortran
      - run: scl enable devtoolset-2 bash
      - run: source /opt/rh/devtoolset-2/enable
      - run: npm i -g yarn
      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      # run tests!
      - run: yarn test
  #deploy:
    #dockerhub:
      #branch: master
      #commands:
        #- $DOCKER_HUB_TRIGGER
